// Emits a TypeDB 2.28 insert script for the generated dataset.
// datetime literals use YYYY-MM-DDTHH:mm:ss.sss (no zone suffix).

import type { Dataset, Episode, EntityKind } from "../domain/types.ts";

function tqlString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tqlDateTime(iso: string): string {
  const d = new Date(iso);
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mi = String(d.getUTCMinutes()).padStart(2, "0");
  const ss = String(d.getUTCSeconds()).padStart(2, "0");
  const ms = String(d.getUTCMilliseconds()).padStart(3, "0");
  return `${yyyy}-${mm}-${dd}T${hh}:${mi}:${ss}.${ms}`;
}

function keyAttr(kind: EntityKind): string {
  switch (kind) {
    case "player":   return "player_id";
    case "device":   return "device_id";
    case "location": return "location_id";
    case "npc":      return "npc_id";
    case "mob":      return "mob_id";
    case "item":     return "item_id";
  }
}

export function buildInsertScript(ds: Dataset): string {
  const lines: string[] = [];
  lines.push("# Auto-generated by cmd/mockgen. Do not hand-edit.");
  lines.push("# Load with: scripts/typedb-load.sh\n");

  // Each entity insert is its own logical block — emit a blank line after so
  // load.ts's block splitter treats them independently. TypeDB 3 /v1/query
  // executes only the first statement per request, so one-block-per-request
  // loading is mandatory for correctness.
  const blank = () => lines.push("");
  for (const p of ds.players) {
    lines.push(`insert $x isa player, has player_id ${tqlString(p.id)}, has username ${tqlString(p.username)};`);
    blank();
  }
  for (const d of ds.devices) {
    lines.push(`insert $x isa device, has device_id ${tqlString(d.id)}, has device_type ${tqlString(d.kind)};`);
    blank();
  }
  for (const l of ds.locations) {
    lines.push(`insert $x isa location, has location_id ${tqlString(l.id)}, has zone_name ${tqlString(l.name)};`);
    blank();
  }
  for (const n of ds.npcs) {
    lines.push(`insert $x isa npc, has npc_id ${tqlString(n.id)}, has npc_kind ${tqlString(n.kind)};`);
    blank();
  }
  for (const m of ds.mobs) {
    lines.push(`insert $x isa mob, has mob_id ${tqlString(m.id)}, has mob_species ${tqlString(m.species)};`);
    blank();
  }
  for (const it of ds.items) {
    lines.push(`insert $x isa item, has item_id ${tqlString(it.id)}, has item_kind ${tqlString(it.kind)};`);
    blank();
  }
  lines.push("", "# -------------------- episodes -------------------- ", "");

  for (const ep of ds.episodes) {
    lines.push(writeEpisode(ep));
  }
  return lines.join("\n");
}

function writeEpisode(ep: Episode): string {
  const seen: Record<string, string> = {};
  const bindings: { varName: string; role: string; kind: EntityKind; id: string }[] = [];
  let idx = 0;
  for (const r of ep.roles) {
    let v = seen[r.entity_id];
    if (!v) {
      v = `$v${idx++}`;
      seen[r.entity_id] = v;
    }
    bindings.push({ varName: v, role: r.role, kind: r.entity_kind, id: r.entity_id });
  }

  const matchLines: string[] = [];
  const matched = new Set<string>();
  for (const b of bindings) {
    if (matched.has(b.id)) continue;
    matched.add(b.id);
    matchLines.push(`  ${b.varName} isa ${b.kind}, has ${keyAttr(b.kind)} ${tqlString(b.id)};`);
  }

  const linkParts = bindings.map((b) => `${b.role}: ${b.varName}`).join(", ");
  const boolStr = (b: boolean) => b ? "true" : "false";

  return [
    "match",
    ...matchLines,
    "insert",
    `  (${linkParts}) isa episode,`,
    `    has ns_id ${tqlString(ep.ns_id)},`,
    `    has relation_type ${tqlString(ep.relation_type)},`,
    `    has event_time ${tqlDateTime(ep.event_time)},`,
    `    has minute_bucket ${ep.minute_bucket},`,
    `    has hour_bucket ${ep.hour_bucket},`,
    `    has valid_from ${tqlDateTime(ep.valid_from)},`,
    `    has valid_until ${tqlDateTime(ep.valid_until)},`,
    `    has importance ${ep.importance.toFixed(4)},`,
    `    has belief ${ep.belief.toFixed(4)},`,
    `    has crosses_minute ${boolStr(ep.crosses_minute)},`,
    `    has crosses_hour ${boolStr(ep.crosses_hour)},`,
    `    has activity_type ${tqlString(ep.activity_type)},`,
    `    has mood ${tqlString(ep.mood)},`,
    `    has community_id ${tqlString(ep.community_id)},`,
    `    has source_ref ${tqlString(ep.source_ref)};`,
    "",
  ].join("\n");
}
