#!/usr/bin/env bash
# Create database `n_ary` (if missing), apply schema, and ingest generated data
# through the TypeDB 3.x HTTP API. Runs from WSL but relies on the host's
# published port (docker-compose maps container 8000 -> host 8000).
#
# Expects:
#   - scripts/typedb-up.sh has launched the container
#   - backend/out/insert.tql generated by `bun run src/cmd/mockgen.ts`
#
# Usage: bash scripts/typedb-load.sh [--reset]

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v bun >/dev/null 2>&1; then
  echo "!! bun is required in PATH"
  exit 1
fi

cd "$ROOT_DIR/backend"
bun run src/cmd/load.ts "$@"
